spring.application.name=quiz
server.port=8080

spring.datasource.url=jdbc:postgresql://ep-weathered-resonance-aqermsjx-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NTHYdbV7PoX0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

